### PR TITLE
landing-page

### PR DESCRIPTION
**Pull request by KaustubhM1997**
completed the landing page

### CODE REVIEW

**Review by Amandeep-sinha — APPROVED** [review]
Looks Good

**Comment by horsemaker** [comment]
Looks clean! 👍

**Review by vijaytembugade — APPROVED** [review]
Roger it! Looks preety well!

**Comment by preethasri** [comment]
looks neat and good work kaustubh

**Review by KoushikKintali — APPROVED** [review]
looks good

**Review by srishti-maurya — COMMENTED** [review]
UI looks clean and elegant👍

**Pull request merged**
